# fly.toml app configuration file generated for consumoapi on 2023-08-04T18:22:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "consumoapi"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
